- name: "Create data directory"
  file:
    path: /home/ubuntu/data
    mode: '0755'
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Create cert directory"
  file:
    path: /home/ubuntu/cert
    mode: '0600'
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Copy over nginx"
  synchronize:
    src: "{{ role_path }}/prep/nginx"
    dest: /home/ubuntu/

- name: "Render the docker-compose file"
  template:
    src: "docker-compose.yml.j2"
    dest: /home/ubuntu/docker-compose.yml
    mode: '0700'
    owner: "ubuntu"
    group: "ubuntu"
